package generator

import (
	"fmt"
	rc "gorepogen/internal/repocomp"
	"os"
	"path/filepath"
	"strings"

	j "github.com/dave/jennifer/jen"
)

// CreateNamesRegistry build full list of needed names
// needed for auto generation
func CreateNamesRegistry(entityInfo *entityInfo) NamesRegistry {
	entityNameUncapitalized := strings.ToLower(entityInfo.Name)
	entityName := entityInfo.Name
	return NamesRegistry{
		EntityName:            entityName,
		PackageName:           entityInfo.Package,
		FullPackageName:       entityInfo.FullPackagePath,
		EntityNameWithPackage: fmt.Sprintf("%s.%s", entityInfo.Package, entityName),
		InterfaceName:         fmt.Sprintf("%sRepository", entityName),
		ConstructorName:       fmt.Sprintf("New%sRepository", entityName),
		StructName:            fmt.Sprintf("%sRepository", entityNameUncapitalized),
		ReceiveName:           fmt.Sprintf("r %sRepository", entityNameUncapitalized),
		FileName:              fmt.Sprintf("%s_repository.go", entityNameUncapitalized),
		RepositoryPackageName: "repository",
	}
}

// AssignNamesToComponents provides full list of names to each component
func AssignNamesToComponents(namesRegistry NamesRegistry) []rc.Appender {
	return []rc.Appender{
		rc.NewInterface(namesRegistry.GetInterfaceNames()),
		rc.NewStruct(namesRegistry.GetStructNames()),
		rc.NewConstructor(namesRegistry.GetConstructorNames()),
		rc.NewMethodsList(namesRegistry.GetMethodListNames()),
	}
}

// Generate perform final rendering from all components
func Generate(components []rc.Appender, namesRegistry NamesRegistry, currentDir string) (string, error) {

	repositoryPackageName := namesRegistry.RepositoryPackageName
	file := j.NewFile(repositoryPackageName)
	file.HeaderComment("THIS FILE IS AUTOGENERATED.")
	file.HeaderComment("FEEL FREE TO CHANGE IT.")
	file.HeaderComment("GOREPOGEN 1.0.0")
	file.ImportName("github.com/jinzhu/gorm", "gorm")
	file.ImportName(namesRegistry.FullPackageName, namesRegistry.PackageName)

	for _, c := range components {
		c.AppendTo(file)
	}

	repositoryDir := makeRepositoryDir(currentDir, repositoryPackageName)
	repositoryFullPath := filepath.Join(repositoryDir, namesRegistry.FileName)

	return repositoryFullPath, file.Save(repositoryFullPath)
}

func makeRepositoryDir(currentDir string, repositoryPackageName string) string {
	repositoryDir := filepath.Join(currentDir, repositoryPackageName)
	_ = os.MkdirAll(repositoryDir, os.ModePerm)
	return repositoryDir
}
