package generator

import (
	"fmt"
	. "gorepogen/internal/helper"
	. "gorepogen/internal/repocomp"
	"os"
	"path/filepath"
	"strings"

	. "github.com/dave/jennifer/jen"
)

func ResolveNamesRegistry(entityInfo *EntityInfo) NamesRegistry {
	entityNameUncapitalized := strings.ToLower(entityInfo.Name)
	entityName := entityInfo.Name
	return NamesRegistry{
		EntityName:            entityName,
		PackageName:           entityInfo.Package,
		FullPackageName:       entityInfo.FullPackagePath,
		EntityNameWithPackage: fmt.Sprintf("%s.%s", entityInfo.Package, entityName),
		InterfaceName:         fmt.Sprintf("%sRepository", entityName),
		ConstructorName:       fmt.Sprintf("New%sRepository", entityName),
		StructName:            fmt.Sprintf("%sRepository", entityNameUncapitalized),
		ReceiveName:           fmt.Sprintf("r %sRepository", entityNameUncapitalized),
		FileName:              fmt.Sprintf("%s_repository.go", entityNameUncapitalized),
		RepositoryPackageName: "repository",
	}
}

func AssignNamesToComponents(namesRegistry NamesRegistry) []Appender {
	return []Appender{
		NewInterface(namesRegistry.GetInterfaceNames()),
		NewStruct(namesRegistry.GetStructNames()),
		NewConstructor(namesRegistry.GetConstructorNames()),
		NewMethodsList(namesRegistry.GetMethodListNames()),
	}
}

func Generate(components []Appender, namesRegistry NamesRegistry, currentDir string) (string, error) {

	repositoryPackageName := namesRegistry.RepositoryPackageName
	file := NewFile(repositoryPackageName)
	file.HeaderComment("THIS FILE IS AUTOGENERATED. GOREPOGEN 1.0.0")
	file.ImportName("github.com/jinzhu/gorm", "gorm")
	file.ImportName(namesRegistry.FullPackageName, namesRegistry.PackageName)

	for _, c := range components {
		c.AppendTo(file)
	}

	repositoryDir := makeRepositoryDir(currentDir, repositoryPackageName)
	repositoryFullPath := filepath.Join(repositoryDir, namesRegistry.FileName)

	return repositoryFullPath, file.Save(repositoryFullPath)
}

func makeRepositoryDir(currentDir string, repositoryPackageName string) string {
	repositoryDir := filepath.Join(currentDir, repositoryPackageName)
	_ = os.MkdirAll(repositoryDir, os.ModePerm)
	return repositoryDir
}
